# Generated by Django 2.2.17 on 2020-11-08 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_work'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
