# Generated by Django 2.2.17 on 2020-12-15 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='parcentage',
            new_name='percentage',
        ),
    ]
