# Generated by Django 2.2.17 on 2020-12-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201215_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30, verbose_name='著者名')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description', models.CharField(max_length=200, verbose_name='詳細')),
                ('image', models.ImageField(upload_to='images', verbose_name='イメージ画像')),
                ('time', models.CharField(max_length=30, verbose_name='執筆時間')),
            ],
        ),
    ]
